name: marvel_heroes_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/movies/
    - assets/chars/
    - assets/icons/
  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/gilroy-bold.ttf
        - asset: assets/fonts/gilroy-heavy.ttf
        - asset: assets/fonts/gilroy-medium.ttf
        - asset: assets/fonts/gilroy-regular.ttf
        - asset: assets/fonts/gilroy-semibold.ttf
